import json,pathlib
p=pathlib.Path('/home/rm01/Qwen3x-Orin/.q3x-work/decode-product-20260927')
b=json.loads((p/'numeric-p1089-scalar.json').read_text());c=json.loads((p/'numeric-p1089-fused.json').read_text())
rows={mode:[json.loads(x) for x in (p/f'numeric-p1089-{mode}.json.attention.jsonl').read_text().splitlines()] for mode in ('scalar','fused')}
x={'scope':'P1089/O16 bounded numerical admission; no model capability or production qualification','same_prompt':b['prompt_ids']==c['prompt_ids'],'same_generation':b['generated_ids']==c['generated_ids'],'same_prefix':b['terminal_prefix_observation']==c['terminal_prefix_observation'],'full_logit_hashes_equal':[u['full_bf16_logits_sha256']==v['full_bf16_logits_sha256'] for u,v in zip(b['steps'],c['steps'])],'prefill_state_fields_equal':{k:b['prefill_commit'][k]==c['prefill_commit'][k] for k in b['prefill_commit']},'return_state_fields_equal':{k:b['generation_return'][k]==c['generation_return'][k] for k in b['generation_return']},'attention':{mode:{'observations':len(a),'max_relative_l2_vs_scalar':max(t['relative_l2_vs_scalar'] for t in a),'repeat_exact':all(t['repeat_equal'] for t in a),'nonfinite':sum(t['nonfinite'] for t in a),'independent_fp64':[t for t in a if 'fp64_heads' in t]} for mode,a in rows.items()},'limits':['Only first-step four layers and two heads have an independent FP64 oracle.','Full vocabulary hashes detect difference but do not quantify logit error.','Both free-running trajectories happened to use identical token inputs for this workload; no general teacher-forcing harness is claimed.','No public capability score or long-context numerical acceptance.']}
(p/'numerical-summary.json').write_text(json.dumps(x,indent=2))
assert x['same_prompt'] and x['same_generation'] and x['same_prefix']
assert all(v['observations']==256 and v['repeat_exact'] and not v['nonfinite'] and v['max_relative_l2_vs_scalar']<=1/128 for v in x['attention'].values())
print('PASS bounded admission; exact full-model equivalence fails, no promotion')
