if(NOT DEFINED Q3X_PROVENANCE_SOURCE_DIR OR
   NOT DEFINED Q3X_PROVENANCE_GIT_EXECUTABLE OR
   NOT DEFINED Q3X_PROVENANCE_TEMPLATE OR
   NOT DEFINED Q3X_PROVENANCE_OUTPUT)
  message(FATAL_ERROR "incomplete MacroFeed V4 lifetime provenance inputs")
endif()

execute_process(
  COMMAND "${Q3X_PROVENANCE_GIT_EXECUTABLE}" -C
          "${Q3X_PROVENANCE_SOURCE_DIR}" rev-parse HEAD
  OUTPUT_VARIABLE Q3X_PROVENANCE_GIT_COMMIT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE git_commit_status
  ERROR_VARIABLE git_commit_error
)
execute_process(
  COMMAND "${Q3X_PROVENANCE_GIT_EXECUTABLE}" -C
          "${Q3X_PROVENANCE_SOURCE_DIR}" rev-parse "HEAD^{tree}"
  OUTPUT_VARIABLE Q3X_PROVENANCE_GIT_TREE
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE git_tree_status
  ERROR_VARIABLE git_tree_error
)
execute_process(
  COMMAND "${Q3X_PROVENANCE_GIT_EXECUTABLE}" -C
          "${Q3X_PROVENANCE_SOURCE_DIR}" status --porcelain=v1
          --untracked-files=all
  OUTPUT_VARIABLE git_status_porcelain
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE git_status_status
  ERROR_VARIABLE git_status_error
)
if(NOT git_commit_status EQUAL 0 OR NOT git_tree_status EQUAL 0 OR
   NOT git_status_status EQUAL 0)
  message(FATAL_ERROR
    "cannot freeze MacroFeed V4 lifetime git provenance: "
    "${git_commit_error}${git_tree_error}${git_status_error}"
  )
endif()

if(git_status_porcelain STREQUAL "")
  set(Q3X_PROVENANCE_GIT_CLEAN true)
else()
  set(Q3X_PROVENANCE_GIT_CLEAN false)
endif()

if(EXISTS "${Q3X_PROVENANCE_CXX_COMPILER}")
  file(SHA256 "${Q3X_PROVENANCE_CXX_COMPILER}"
       Q3X_PROVENANCE_CXX_COMPILER_SHA256)
else()
  set(Q3X_PROVENANCE_CXX_COMPILER_SHA256 "unavailable")
endif()
if(EXISTS "${Q3X_PROVENANCE_CUDA_COMPILER}")
  file(SHA256 "${Q3X_PROVENANCE_CUDA_COMPILER}"
       Q3X_PROVENANCE_CUDA_COMPILER_SHA256)
else()
  set(Q3X_PROVENANCE_CUDA_COMPILER_SHA256 "unavailable")
endif()

foreach(boolean_name IN ITEMS
    Q3X_PROVENANCE_BUILD_TESTING
    Q3X_PROVENANCE_MACROFEED_V3_P40_EXECUTOR_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_STARTUP_PACKAGE_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_EXECUTION_EVENTS_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_EXECUTION_PACKAGE_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_NORM_RESIDUAL_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_BF16_AB_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_FP8_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_GDN_C8000_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_NVFP4_GATE_UP_ADMISSION
    Q3X_PROVENANCE_MACROFEED_V4_NVFP4_DOWN_ADMISSION
    Q3X_PROVENANCE_TARGET_AOT_COMPLETE_DEVICE_ASSETS_V2_ADMISSION)
  if(${boolean_name})
    set(${boolean_name} true)
  else()
    set(${boolean_name} false)
  endif()
endforeach()

set(Q3X_PROVENANCE_BUILD_RECEIPT_SCHEMA
    "q3x.sm87.macrofeed-v4.engine-lifetime-build.v1")
string(CONCAT build_receipt
  "schema=${Q3X_PROVENANCE_BUILD_RECEIPT_SCHEMA}\n"
  "git_commit=${Q3X_PROVENANCE_GIT_COMMIT}\n"
  "git_tree=${Q3X_PROVENANCE_GIT_TREE}\n"
  "git_clean=${Q3X_PROVENANCE_GIT_CLEAN}\n"
  "cmake_version=${Q3X_PROVENANCE_CMAKE_VERSION}\n"
  "generator=${Q3X_PROVENANCE_GENERATOR}\n"
  "build_type=${Q3X_PROVENANCE_BUILD_TYPE}\n"
  "build_testing=${Q3X_PROVENANCE_BUILD_TESTING}\n"
  "q3x_cuda_architectures=${Q3X_PROVENANCE_Q3X_CUDA_ARCHITECTURES}\n"
  "effective_cuda_architectures=${Q3X_PROVENANCE_EFFECTIVE_CUDA_ARCHITECTURES}\n"
  "cxx_compiler=${Q3X_PROVENANCE_CXX_COMPILER}\n"
  "cxx_compiler_id=${Q3X_PROVENANCE_CXX_COMPILER_ID}\n"
  "cxx_compiler_version=${Q3X_PROVENANCE_CXX_COMPILER_VERSION}\n"
  "cxx_compiler_sha256=${Q3X_PROVENANCE_CXX_COMPILER_SHA256}\n"
  "cuda_compiler=${Q3X_PROVENANCE_CUDA_COMPILER}\n"
  "cuda_compiler_id=${Q3X_PROVENANCE_CUDA_COMPILER_ID}\n"
  "cuda_compiler_version=${Q3X_PROVENANCE_CUDA_COMPILER_VERSION}\n"
  "cuda_compiler_sha256=${Q3X_PROVENANCE_CUDA_COMPILER_SHA256}\n"
  "cuda_toolkit_version=${Q3X_PROVENANCE_CUDA_TOOLKIT_VERSION}\n"
  "cxx_release_flags=${Q3X_PROVENANCE_CXX_RELEASE_FLAGS}\n"
  "cuda_release_flags=${Q3X_PROVENANCE_CUDA_RELEASE_FLAGS}\n"
  "cxx_global_flags=${Q3X_PROVENANCE_CXX_GLOBAL_FLAGS}\n"
  "cuda_global_flags=${Q3X_PROVENANCE_CUDA_GLOBAL_FLAGS}\n"
  "macrofeed_v3_executor=${Q3X_PROVENANCE_MACROFEED_V3_P40_EXECUTOR_ADMISSION}\n"
  "macrofeed_v4_startup=${Q3X_PROVENANCE_MACROFEED_V4_STARTUP_PACKAGE_ADMISSION}\n"
  "macrofeed_v4_events=${Q3X_PROVENANCE_MACROFEED_V4_EXECUTION_EVENTS_ADMISSION}\n"
  "macrofeed_v4_execution=${Q3X_PROVENANCE_MACROFEED_V4_EXECUTION_PACKAGE_ADMISSION}\n"
  "macrofeed_v4_norm=${Q3X_PROVENANCE_MACROFEED_V4_NORM_RESIDUAL_ADMISSION}\n"
  "macrofeed_v4_bf16_ab=${Q3X_PROVENANCE_MACROFEED_V4_BF16_AB_ADMISSION}\n"
  "macrofeed_v4_fp8=${Q3X_PROVENANCE_MACROFEED_V4_FP8_ADMISSION}\n"
  "macrofeed_v4_gdn=${Q3X_PROVENANCE_MACROFEED_V4_GDN_C8000_ADMISSION}\n"
  "macrofeed_v4_gate_up=${Q3X_PROVENANCE_MACROFEED_V4_NVFP4_GATE_UP_ADMISSION}\n"
  "macrofeed_v4_down=${Q3X_PROVENANCE_MACROFEED_V4_NVFP4_DOWN_ADMISSION}\n"
  "target_aot_complete_assets=${Q3X_PROVENANCE_TARGET_AOT_COMPLETE_DEVICE_ASSETS_V2_ADMISSION}\n"
)
string(SHA256 Q3X_PROVENANCE_BUILD_RECEIPT_SHA256 "${build_receipt}")

foreach(value_name IN ITEMS
    Q3X_PROVENANCE_GIT_COMMIT
    Q3X_PROVENANCE_GIT_TREE
    Q3X_PROVENANCE_CMAKE_VERSION
    Q3X_PROVENANCE_GENERATOR
    Q3X_PROVENANCE_BUILD_TYPE
    Q3X_PROVENANCE_Q3X_CUDA_ARCHITECTURES
    Q3X_PROVENANCE_EFFECTIVE_CUDA_ARCHITECTURES
    Q3X_PROVENANCE_CXX_COMPILER
    Q3X_PROVENANCE_CXX_COMPILER_ID
    Q3X_PROVENANCE_CXX_COMPILER_VERSION
    Q3X_PROVENANCE_CXX_COMPILER_SHA256
    Q3X_PROVENANCE_CUDA_COMPILER
    Q3X_PROVENANCE_CUDA_COMPILER_ID
    Q3X_PROVENANCE_CUDA_COMPILER_VERSION
    Q3X_PROVENANCE_CUDA_COMPILER_SHA256
    Q3X_PROVENANCE_CUDA_TOOLKIT_VERSION
    Q3X_PROVENANCE_CXX_RELEASE_FLAGS
    Q3X_PROVENANCE_CUDA_RELEASE_FLAGS
    Q3X_PROVENANCE_CXX_GLOBAL_FLAGS
    Q3X_PROVENANCE_CUDA_GLOBAL_FLAGS
    Q3X_PROVENANCE_BUILD_RECEIPT_SCHEMA
    Q3X_PROVENANCE_BUILD_RECEIPT_SHA256)
  string(REPLACE "\\" "\\\\" ${value_name} "${${value_name}}")
  string(REPLACE "\"" "\\\"" ${value_name} "${${value_name}}")
  string(REPLACE "\n" "\\n" ${value_name} "${${value_name}}")
endforeach()

get_filename_component(output_directory "${Q3X_PROVENANCE_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
set(temporary_output "${Q3X_PROVENANCE_OUTPUT}.tmp")
configure_file("${Q3X_PROVENANCE_TEMPLATE}" "${temporary_output}" @ONLY)
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different
          "${temporary_output}" "${Q3X_PROVENANCE_OUTPUT}"
  RESULT_VARIABLE copy_status
)
file(REMOVE "${temporary_output}")
if(NOT copy_status EQUAL 0)
  message(FATAL_ERROR
    "cannot publish MacroFeed V4 lifetime provenance header")
endif()
